[main]
keepcache=1
retries=20
gpgcheck=1
install_weak_deps=0
metadata_expire=-1
best=1
tsflags=nodocs
max_parallel_downloads=20
reposdir=/dev/null

[terra]
name=Terra $releasever
baseurl=https://repos-cf.fyralabs.com/terra$releasever
metadata_expire=0
type=rpm
gpgkey=https://repos-cf.fyralabs.com/terra$releasever/key.asc
repo_gpgcheck=1
enabled=1
enabled_metadata=1

[terra-extras]
name=Terra $releasever (Extras)
baseurl=https://repos-cf.fyralabs.com/terra$releasever-extras
metadata_expire=0
type=rpm
gpgkey=https://repos-cf.fyralabs.com/terra$releasever-extras/key.asc
repo_gpgcheck=1
enabled=1
enabled_metadata=1
priority=150

[terra-nvidia]
name=Terra $releasever (NVIDIA)
baseurl=https://repos-cf.fyralabs.com/terra$releasever-nvidia
metadata_expire=0
type=rpm
gpgkey=https://repos-cf.fyralabs.com/terra$releasever-nvidia/key.asc
repo_gpgcheck=1
enabled=0
enabled_metadata=1
priority=80

[terra-mesa]
name=Terra $releasever (Mesa)
baseurl=https://repos-cf.fyralabs.com/terra$releasever-mesa
type=rpm
gpgkey=https://repos-cf.fyralabs.com/terra$releasever-mesa/key.asc
repo_gpgcheck=1
enabled=1
enabled_metadata=1
priority=80

[fedora]
name=Fedora $releasever - $basearch
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[updates]
name=updates
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[adoptium-temurin-java-repository]
name=Adoptium
baseurl=https://packages.adoptium.net/artifactory/rpm/fedora/$releasever/$basearch
enabled=1
gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public
enabled_metadata=1
